name: wdi5 tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-wdi5:
    runs-on: ubuntu-latest

    steps:
      - name: update chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          # check chrome version
          google-chrome --version

      - name: checkout excelUpload Repo
        uses: actions/checkout@v3

      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1

      - name: use node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      # we need this for workspace mgmt
      - name: check npm version >= 7
        run: npm --version

      - name: update npm
        run: |
          npm i -g npm@latest
          npm --version

      - name: pnpm install
        run: |
          pnpm install

      - name: Run Build
        run: npm run build

      # update chromedriver
      - name: update chromedriver to latest
        run: |
          npm run updateChromedriver

      - name: install @sap/cds-dk
        run: |
          npm i -g @sap/cds-dk

      # run app
      - name: start cap server
        run: npm run start:server&

      - name: start test apps
        run: |
          npm run startv2fe&
          npm run startv4&

      # run wdi5 tests
      - name: test wdi5 v2 ui5 108
        run: npm run testv2108Headless

      - name: kill CAP Server
        run: |
          pkill -f "@sap/cds-dk/bin/watch.js"

      - name: start CAP Server
        run: |
          npm run start:server&

      # run wdi5 tests
      - name: test wdi5 v2 ui5 96
        run: npm run testv296Headless
      
      - name: kill CAP Server
        run: |
          pkill -f "@sap/cds-dk/bin/watch.js"

      - name: start CAP Server
        run: |
          npm run start:server&

      # run wdi5 tests
      - name: test wdi5 v2 ui5 84
        run: npm run testv284Headless

      - name: kill CAP Server
        run: |
          pkill -f "@sap/cds-dk/bin/watch.js"

      - name: start CAP Server
        run: |
          npm run start:server&

      # run wdi5 tests
      - name: test wdi5 v4
        run: npm run testv4Headless
